import { MessageType } from './types';

export const exampleMessageList = [
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Пока!' },
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Пока!' },
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.INFO, text: '100 лет назад' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Первое сообщение' },
  { type: MessageType.MY, text: 'Это моё тестовое сообщение, которое находится с правой стороны :3' },
  { type: MessageType.INFO, text: 'Сегодня' },
  { type: MessageType.CONTACT, text: 'Это будет супер длинное сообщение Это будет супер длинное сообщение' },
  { type: MessageType.CONTACT, text: 'Пока!' }
];

export const userList = [
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' },
  { name: 'Пользователь', lastMessage: 'Пока!' }
];
